; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Mobile GamePad"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Neider Gainza Llacer"
#define MyAppURL "https://neidergainza.github.io/gamepad_releases"
#define MyAppExeName "desktop.exe"
#define PackageDir SourcePath

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{97171654-8041-45FB-B728-C3D66D2E7293}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
PrivilegesRequired=admin
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir="{#PackageDir}\Output"
OutputBaseFilename=MobileGamePad-Setup
SetupIconFile="{#PackageDir}\..\..\desktop\windows\runner\resources\app_icon.ico"
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PackageDir}\desktop\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackageDir}\server\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#PackageDir}\ViGEmBus_1.22.0_x64_x86_arm64.exe"; DestDir: "{tmp}"; Flags: dontcopy
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
	ResultCode: Integer;
begin
	Result := '';
	if RegKeyExists(HKLM, 'SYSTEM\CurrentControlSet\Services\ViGEmBus') and
		FileExists(ExpandConstant('{sys}\drivers\ViGEmBus.sys')) then
		Exit;

	ExtractTemporaryFile('ViGEmBus_1.22.0_x64_x86_arm64.exe');

	if not Exec(
		ExpandConstant('{tmp}\ViGEmBus_1.22.0_x64_x86_arm64.exe'),
		'/exenoui /qn /norestart',
		'',
		SW_SHOW,
		ewWaitUntilTerminated,
		ResultCode) then
	begin
		Result := 'Could not start the ViGEmBus driver installer.';
	end
	else if (ResultCode <> 0) and (ResultCode <> 3010) then
	begin
		Result := Format('ViGEmBus installation failed with exit code %d.', [ResultCode]);
	end
	else if ResultCode = 3010 then
	begin
		NeedsRestart := True;
	end;
end;

