// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// @brief Libera los recursos del dispositivo y destruye el nodo uinput
/// @param fd Descriptor de archivo
/// @return 0 en éxito
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int close_device(int fd);

/// @brief Asigna el nombre al dispositivo y lo registra en el sistema
/// @param fd Descriptor de archivo
/// @param identifier Identificador para formar "Player [identifier]
/// @param vendor Marca de fabricante dispositivo a emular (0x045E XBox)
/// @param product Modelo de dispositivo (0x028E XBox One (no idea))
/// @return 0 en éxito, -1 en error
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int)>()
external int create_device(int fd, int identifier, int vendor, int product);

/// @brief calls ioctl(fd, UI_SET_ABSBIT, value)
/// @param fd Descriptor de archivo
/// @param axis Código del eje (ej: ABS_X)
/// @param minimum Valor mínimo del eje
/// @param maximum Valor máximo del eje
/// @param fuzz Tolerancia de ruido del eje
/// @param flat Zona muerta del eje
/// @param resolution Resolución del eje
/// @return 0 en éxito, -1 en error
@ffi.Native<
  ffi.Int Function(
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Int,
  )
>()
external int ioctl_ui_set_absbit(
  int fd,
  int axis,
  int minimum,
  int maximum,
  int fuzz,
  int flat,
  int resolution,
);

/// @brief calls ioctl(fd, UI_SET_EVBIT, ev)
/// @param fd file descriptor
/// @param ev evento (EV_KEY,EV_ABS,EV_FF,)
/// @return -1 if failed , 0 if success
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int ioctl_ui_set_evbit(int fd, int ev);

/// @brief calls ioctl(fd, UI_SET_FFBIT, value)
/// @param fd Descriptor de archivo
/// @param value Código del eje (ej: ABS_X)
/// @return 0 en éxito, -1 en error
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int ioctl_ui_set_ffbit(int fd, int value);

/// @brief calls ioctl(fd, UI_SET_KEYBIT, value)
/// @param fd Descriptor de archivo obtenido con open_device
/// @param value Código de la tecla/botón/eje (ej: BTN_A, ABS_X)
/// @return 0 en éxito, -1 en error
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int ioctl_ui_set_keybit(int fd, int value);

/// @brief calls ioctl(fd, UI_SET_RELBIT, value)
/// @param fd Descriptor de archivo obtenido con open_device
/// @param value Código de la tecla/botón/eje (ej: BTN_A, ABS_X)
/// @return 0 en éxito, -1 en error
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int)>()
external int ioctl_ui_set_relbit(int fd, int value);

/// @brief Envia evento de mover axis (la accion se ejecuta en el proximo sync)
/// @param fd Descriptor de archivo
/// @param axis Código del eje (ABS_*)
/// @param value Valor del eje
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>()
external int move_axis(int fd, int axis, int value);

/// @brief Abre /dev/uinput y prepara la sesión
/// @return file descriptor (fd) o -1 en caso de error
@ffi.Native<ffi.Int Function()>()
external int open_device();

/// @brief Envía el evento de presionar/liberar botón
/// (la accion se ejecuta en el proximo sync)
/// @param fd Descriptor de archivo
/// @param button Código del botón (BTN_*)
/// @param value 0 para liberar, 1 para presionar
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int)>()
external int press_button(int fd, int button, int value);

/// @brief Lee un evento generado por el dispositivo virtual.
/// @param fd Descriptor de archivo obtenido con open_device
/// @param type Tipo del evento (EV_UINPUT, EV_FF, etc.)
/// @param code Código del evento
/// @param value Valor del evento
/// @return 0 si se leyó un evento, -1 si ocurrió un error
@ffi.Native<
  ffi.Int Function(
    ffi.Int,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
  )
>()
external int read_input_event(
  int fd,
  ffi.Pointer<ffi.Int> type,
  ffi.Pointer<ffi.Int> code,
  ffi.Pointer<ffi.Int> value,
);

/// @brief Sincroniza los movimientos
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int sync_device(int fd);

const int ABS_BRAKE = 10;

const int ABS_CNT = 64;

const int ABS_DISTANCE = 25;

const int ABS_GAS = 9;

const int ABS_HAT0X = 16;

const int ABS_HAT0Y = 17;

const int ABS_HAT1X = 18;

const int ABS_HAT1Y = 19;

const int ABS_HAT2X = 20;

const int ABS_HAT2Y = 21;

const int ABS_HAT3X = 22;

const int ABS_HAT3Y = 23;

const int ABS_MAX = 63;

const int ABS_MISC = 40;

const int ABS_MT_BLOB_ID = 56;

const int ABS_MT_DISTANCE = 59;

const int ABS_MT_ORIENTATION = 52;

const int ABS_MT_POSITION_X = 53;

const int ABS_MT_POSITION_Y = 54;

const int ABS_MT_PRESSURE = 58;

const int ABS_MT_SLOT = 47;

const int ABS_MT_TOOL_TYPE = 55;

const int ABS_MT_TOOL_X = 60;

const int ABS_MT_TOOL_Y = 61;

const int ABS_MT_TOUCH_MAJOR = 48;

const int ABS_MT_TOUCH_MINOR = 49;

const int ABS_MT_TRACKING_ID = 57;

const int ABS_MT_WIDTH_MAJOR = 50;

const int ABS_MT_WIDTH_MINOR = 51;

const int ABS_PRESSURE = 24;

const int ABS_PROFILE = 33;

const int ABS_RESERVED = 46;

const int ABS_RUDDER = 7;

const int ABS_RX = 3;

const int ABS_RY = 4;

const int ABS_RZ = 5;

const int ABS_SND_PROFILE = 34;

const int ABS_THROTTLE = 6;

const int ABS_TILT_X = 26;

const int ABS_TILT_Y = 27;

const int ABS_TOOL_WIDTH = 28;

const int ABS_VOLUME = 32;

const int ABS_WHEEL = 8;

const int ABS_X = 0;

const int ABS_Y = 1;

const int ABS_Z = 2;

const int BTN_0 = 256;

const int BTN_1 = 257;

const int BTN_2 = 258;

const int BTN_3 = 259;

const int BTN_4 = 260;

const int BTN_5 = 261;

const int BTN_6 = 262;

const int BTN_7 = 263;

const int BTN_8 = 264;

const int BTN_9 = 265;

const int BTN_A = 304;

const int BTN_B = 305;

const int BTN_BACK = 278;

const int BTN_BASE = 294;

const int BTN_BASE2 = 295;

const int BTN_BASE3 = 296;

const int BTN_BASE4 = 297;

const int BTN_BASE5 = 298;

const int BTN_BASE6 = 299;

const int BTN_C = 306;

const int BTN_DEAD = 303;

const int BTN_DIGI = 320;

const int BTN_DPAD_DOWN = 545;

const int BTN_DPAD_LEFT = 546;

const int BTN_DPAD_RIGHT = 547;

const int BTN_DPAD_UP = 544;

const int BTN_EAST = 305;

const int BTN_EXTRA = 276;

const int BTN_FORWARD = 277;

const int BTN_GAMEPAD = 304;

const int BTN_GEAR_DOWN = 336;

const int BTN_GEAR_UP = 337;

const int BTN_GRIPL = 548;

const int BTN_GRIPL2 = 550;

const int BTN_GRIPR = 549;

const int BTN_GRIPR2 = 551;

const int BTN_JOYSTICK = 288;

const int BTN_LEFT = 272;

const int BTN_MIDDLE = 274;

const int BTN_MISC = 256;

const int BTN_MODE = 316;

const int BTN_MOUSE = 272;

const int BTN_NORTH = 307;

const int BTN_PINKIE = 293;

const int BTN_RIGHT = 273;

const int BTN_SELECT = 314;

const int BTN_SIDE = 275;

const int BTN_SOUTH = 304;

const int BTN_START = 315;

const int BTN_STYLUS = 331;

const int BTN_STYLUS2 = 332;

const int BTN_STYLUS3 = 329;

const int BTN_TASK = 279;

const int BTN_THUMB = 289;

const int BTN_THUMB2 = 290;

const int BTN_THUMBL = 317;

const int BTN_THUMBR = 318;

const int BTN_TL = 310;

const int BTN_TL2 = 312;

const int BTN_TOOL_AIRBRUSH = 324;

const int BTN_TOOL_BRUSH = 322;

const int BTN_TOOL_DOUBLETAP = 333;

const int BTN_TOOL_FINGER = 325;

const int BTN_TOOL_LENS = 327;

const int BTN_TOOL_MOUSE = 326;

const int BTN_TOOL_PEN = 320;

const int BTN_TOOL_PENCIL = 323;

const int BTN_TOOL_QUADTAP = 335;

const int BTN_TOOL_QUINTTAP = 328;

const int BTN_TOOL_RUBBER = 321;

const int BTN_TOOL_TRIPLETAP = 334;

const int BTN_TOP = 291;

const int BTN_TOP2 = 292;

const int BTN_TOUCH = 330;

const int BTN_TR = 311;

const int BTN_TR2 = 313;

const int BTN_TRIGGER = 288;

const int BTN_TRIGGER_HAPPY = 704;

const int BTN_TRIGGER_HAPPY1 = 704;

const int BTN_TRIGGER_HAPPY10 = 713;

const int BTN_TRIGGER_HAPPY11 = 714;

const int BTN_TRIGGER_HAPPY12 = 715;

const int BTN_TRIGGER_HAPPY13 = 716;

const int BTN_TRIGGER_HAPPY14 = 717;

const int BTN_TRIGGER_HAPPY15 = 718;

const int BTN_TRIGGER_HAPPY16 = 719;

const int BTN_TRIGGER_HAPPY17 = 720;

const int BTN_TRIGGER_HAPPY18 = 721;

const int BTN_TRIGGER_HAPPY19 = 722;

const int BTN_TRIGGER_HAPPY2 = 705;

const int BTN_TRIGGER_HAPPY20 = 723;

const int BTN_TRIGGER_HAPPY21 = 724;

const int BTN_TRIGGER_HAPPY22 = 725;

const int BTN_TRIGGER_HAPPY23 = 726;

const int BTN_TRIGGER_HAPPY24 = 727;

const int BTN_TRIGGER_HAPPY25 = 728;

const int BTN_TRIGGER_HAPPY26 = 729;

const int BTN_TRIGGER_HAPPY27 = 730;

const int BTN_TRIGGER_HAPPY28 = 731;

const int BTN_TRIGGER_HAPPY29 = 732;

const int BTN_TRIGGER_HAPPY3 = 706;

const int BTN_TRIGGER_HAPPY30 = 733;

const int BTN_TRIGGER_HAPPY31 = 734;

const int BTN_TRIGGER_HAPPY32 = 735;

const int BTN_TRIGGER_HAPPY33 = 736;

const int BTN_TRIGGER_HAPPY34 = 737;

const int BTN_TRIGGER_HAPPY35 = 738;

const int BTN_TRIGGER_HAPPY36 = 739;

const int BTN_TRIGGER_HAPPY37 = 740;

const int BTN_TRIGGER_HAPPY38 = 741;

const int BTN_TRIGGER_HAPPY39 = 742;

const int BTN_TRIGGER_HAPPY4 = 707;

const int BTN_TRIGGER_HAPPY40 = 743;

const int BTN_TRIGGER_HAPPY5 = 708;

const int BTN_TRIGGER_HAPPY6 = 709;

const int BTN_TRIGGER_HAPPY7 = 710;

const int BTN_TRIGGER_HAPPY8 = 711;

const int BTN_TRIGGER_HAPPY9 = 712;

const int BTN_WEST = 308;

const int BTN_WHEEL = 336;

const int BTN_X = 307;

const int BTN_Y = 308;

const int BTN_Z = 309;

const int EV_ABS = 3;

const int EV_CNT = 32;

const int EV_FF = 21;

const int EV_FF_STATUS = 23;

const int EV_KEY = 1;

const int EV_LED = 17;

const int EV_MAX = 31;

const int EV_MSC = 4;

const int EV_PWR = 22;

const int EV_REL = 2;

const int EV_REP = 20;

const int EV_SND = 18;

const int EV_SW = 5;

const int EV_SYN = 0;
