// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:game_controller/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BoxShapeAdapter());
    registerAdapter(ButtonAdapter());
    registerAdapter(ButtonDataAdapter());
    registerAdapter(ButtonGroupAdapter());
    registerAdapter(ButtonTypeAdapter());
    registerAdapter(ControllerAdapter());
    registerAdapter(OffsetAdapter());
    registerAdapter(PlayerAdapter());
    registerAdapter(PlayerButtonAdapter());
    registerAdapter(PositionedButtonGroupAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BoxShapeAdapter());
    registerAdapter(ButtonAdapter());
    registerAdapter(ButtonDataAdapter());
    registerAdapter(ButtonGroupAdapter());
    registerAdapter(ButtonTypeAdapter());
    registerAdapter(ControllerAdapter());
    registerAdapter(OffsetAdapter());
    registerAdapter(PlayerAdapter());
    registerAdapter(PlayerButtonAdapter());
    registerAdapter(PositionedButtonGroupAdapter());
  }
}
