// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

@ffi.Native<PVIGEM_CLIENT Function()>(symbol: 'my_vigem_alloc')
external PVIGEM_CLIENT vigem_alloc();

@ffi.Native<ffi.Int Function(PVIGEM_CLIENT)>(symbol: 'my_vigem_connect')
external int _vigem_connect(PVIGEM_CLIENT client);

VIGEM_ERRORS vigem_connect(PVIGEM_CLIENT client) {
  return VIGEM_ERRORS.fromValue(_vigem_connect(client));
}

@ffi.Native<ffi.Void Function(PVIGEM_CLIENT)>(symbol: 'my_vigem_disconnect')
external void vigem_disconnect(PVIGEM_CLIENT client);

@ffi.Native<ffi.Void Function(PVIGEM_CLIENT)>(symbol: 'my_vigem_free')
external void vigem_free(PVIGEM_CLIENT client);

@ffi.Native<ffi.Int Function(PVIGEM_CLIENT, PVIGEM_TARGET)>(
  symbol: 'my_vigem_target_add',
)
external int _vigem_target_add(PVIGEM_CLIENT client, PVIGEM_TARGET target);

VIGEM_ERRORS vigem_target_add(PVIGEM_CLIENT client, PVIGEM_TARGET target) {
  return VIGEM_ERRORS.fromValue(_vigem_target_add(client, target));
}

@ffi.Native<ffi.Void Function(PVIGEM_TARGET)>(symbol: 'my_vigem_target_free')
external void vigem_target_free(PVIGEM_TARGET target);

@ffi.Native<RumbleState Function(PVIGEM_TARGET)>(
  symbol: 'my_vigem_target_get_rumble',
)
external RumbleState vigem_target_get_rumble(PVIGEM_TARGET target);

@ffi.Native<ffi.Void Function(PVIGEM_CLIENT, PVIGEM_TARGET)>(
  symbol: 'my_vigem_target_remove',
)
external void vigem_target_remove(PVIGEM_CLIENT client, PVIGEM_TARGET target);

@ffi.Native<PVIGEM_TARGET Function()>(symbol: 'my_vigem_target_x360_alloc')
external PVIGEM_TARGET vigem_target_x360_alloc();

@ffi.Native<ffi.Int Function(PVIGEM_CLIENT, PVIGEM_TARGET, XUSB_REPORT)>(
  symbol: 'my_vigem_target_x360_update',
)
external int _vigem_target_x360_update(
  PVIGEM_CLIENT client,
  PVIGEM_TARGET target,
  XUSB_REPORT report,
);

VIGEM_ERRORS vigem_target_x360_update(
  PVIGEM_CLIENT client,
  PVIGEM_TARGET target,
  XUSB_REPORT report,
) {
  return VIGEM_ERRORS.fromValue(
    _vigem_target_x360_update(client, target, report),
  );
}

/// Defines an alias representing a driver connection object
typedef PVIGEM_CLIENT = ffi.Pointer<_VIGEM_CLIENT_T>;

/// Defines an alias representing a target device object
typedef PVIGEM_TARGET = ffi.Pointer<_VIGEM_TARGET_T>;

final class RumbleState extends ffi.Struct {
  @ffi.Uint8()
  external int largeMotor;

  @ffi.Uint8()
  external int smallMotor;

  static ffi.Pointer<RumbleState> $allocate(
    ffi.Allocator $allocator, {
    required int largeMotor,
    required int smallMotor,
  }) => $allocator<RumbleState>()
    ..ref.largeMotor = largeMotor
    ..ref.smallMotor = smallMotor;
}

/// Values that represent ViGEm errors
enum VIGEM_ERRORS {
  VIGEM_ERROR_NONE(536870912),
  VIGEM_ERROR_BUS_NOT_FOUND(-536870911),
  VIGEM_ERROR_NO_FREE_SLOT(-536870910),
  VIGEM_ERROR_INVALID_TARGET(-536870909),
  VIGEM_ERROR_REMOVAL_FAILED(-536870908),
  VIGEM_ERROR_ALREADY_CONNECTED(-536870907),
  VIGEM_ERROR_TARGET_UNINITIALIZED(-536870906),
  VIGEM_ERROR_TARGET_NOT_PLUGGED_IN(-536870905),
  VIGEM_ERROR_BUS_VERSION_MISMATCH(-536870904),
  VIGEM_ERROR_BUS_ACCESS_FAILED(-536870903),
  VIGEM_ERROR_CALLBACK_ALREADY_REGISTERED(-536870896),
  VIGEM_ERROR_CALLBACK_NOT_FOUND(-536870895),
  VIGEM_ERROR_BUS_ALREADY_CONNECTED(-536870894),
  VIGEM_ERROR_BUS_INVALID_HANDLE(-536870893),
  VIGEM_ERROR_XUSB_USERINDEX_OUT_OF_RANGE(-536870892),
  VIGEM_ERROR_INVALID_PARAMETER(-536870891),
  VIGEM_ERROR_NOT_SUPPORTED(-536870890),
  VIGEM_ERROR_WINAPI(-536870889),
  VIGEM_ERROR_TIMED_OUT(-536870888),
  VIGEM_ERROR_IS_DISPOSING(-536870887);

  final int value;
  const VIGEM_ERRORS(this.value);

  static VIGEM_ERRORS fromValue(int value) => switch (value) {
    536870912 => VIGEM_ERROR_NONE,
    -536870911 => VIGEM_ERROR_BUS_NOT_FOUND,
    -536870910 => VIGEM_ERROR_NO_FREE_SLOT,
    -536870909 => VIGEM_ERROR_INVALID_TARGET,
    -536870908 => VIGEM_ERROR_REMOVAL_FAILED,
    -536870907 => VIGEM_ERROR_ALREADY_CONNECTED,
    -536870906 => VIGEM_ERROR_TARGET_UNINITIALIZED,
    -536870905 => VIGEM_ERROR_TARGET_NOT_PLUGGED_IN,
    -536870904 => VIGEM_ERROR_BUS_VERSION_MISMATCH,
    -536870903 => VIGEM_ERROR_BUS_ACCESS_FAILED,
    -536870896 => VIGEM_ERROR_CALLBACK_ALREADY_REGISTERED,
    -536870895 => VIGEM_ERROR_CALLBACK_NOT_FOUND,
    -536870894 => VIGEM_ERROR_BUS_ALREADY_CONNECTED,
    -536870893 => VIGEM_ERROR_BUS_INVALID_HANDLE,
    -536870892 => VIGEM_ERROR_XUSB_USERINDEX_OUT_OF_RANGE,
    -536870891 => VIGEM_ERROR_INVALID_PARAMETER,
    -536870890 => VIGEM_ERROR_NOT_SUPPORTED,
    -536870889 => VIGEM_ERROR_WINAPI,
    -536870888 => VIGEM_ERROR_TIMED_OUT,
    -536870887 => VIGEM_ERROR_IS_DISPOSING,
    _ => throw ArgumentError('Unknown value for VIGEM_ERRORS: $value'),
  };
}

enum VIGEM_TARGET_TYPE {
  Xbox360Wired(0),
  DualShock4Wired(2);

  final int value;
  const VIGEM_TARGET_TYPE(this.value);

  static VIGEM_TARGET_TYPE fromValue(int value) => switch (value) {
    0 => Xbox360Wired,
    2 => DualShock4Wired,
    _ => throw ArgumentError('Unknown value for VIGEM_TARGET_TYPE: $value'),
  };
}

enum XUSB_BUTTON {
  XUSB_GAMEPAD_DPAD_UP(1),
  XUSB_GAMEPAD_DPAD_DOWN(2),
  XUSB_GAMEPAD_DPAD_LEFT(4),
  XUSB_GAMEPAD_DPAD_RIGHT(8),
  XUSB_GAMEPAD_START(16),
  XUSB_GAMEPAD_BACK(32),
  XUSB_GAMEPAD_LEFT_THUMB(64),
  XUSB_GAMEPAD_RIGHT_THUMB(128),
  XUSB_GAMEPAD_LEFT_SHOULDER(256),
  XUSB_GAMEPAD_RIGHT_SHOULDER(512),
  XUSB_GAMEPAD_GUIDE(1024),
  XUSB_GAMEPAD_A(4096),
  XUSB_GAMEPAD_B(8192),
  XUSB_GAMEPAD_X(16384),
  XUSB_GAMEPAD_Y(32768);

  final int value;
  const XUSB_BUTTON(this.value);

  static XUSB_BUTTON fromValue(int value) => switch (value) {
    1 => XUSB_GAMEPAD_DPAD_UP,
    2 => XUSB_GAMEPAD_DPAD_DOWN,
    4 => XUSB_GAMEPAD_DPAD_LEFT,
    8 => XUSB_GAMEPAD_DPAD_RIGHT,
    16 => XUSB_GAMEPAD_START,
    32 => XUSB_GAMEPAD_BACK,
    64 => XUSB_GAMEPAD_LEFT_THUMB,
    128 => XUSB_GAMEPAD_RIGHT_THUMB,
    256 => XUSB_GAMEPAD_LEFT_SHOULDER,
    512 => XUSB_GAMEPAD_RIGHT_SHOULDER,
    1024 => XUSB_GAMEPAD_GUIDE,
    4096 => XUSB_GAMEPAD_A,
    8192 => XUSB_GAMEPAD_B,
    16384 => XUSB_GAMEPAD_X,
    32768 => XUSB_GAMEPAD_Y,
    _ => throw ArgumentError('Unknown value for XUSB_BUTTON: $value'),
  };
}

typedef XUSB_REPORT = _XUSB_REPORT;

final class _VIGEM_CLIENT_T extends ffi.Opaque {}

final class _VIGEM_TARGET_T extends ffi.Opaque {}

final class _XUSB_REPORT extends ffi.Struct {
  @ffi.UnsignedShort()
  external int wButtons;

  @ffi.UnsignedChar()
  external int bLeftTrigger;

  @ffi.UnsignedChar()
  external int bRightTrigger;

  @ffi.Short()
  external int sThumbLX;

  @ffi.Short()
  external int sThumbLY;

  @ffi.Short()
  external int sThumbRX;

  @ffi.Short()
  external int sThumbRY;
}
